openapi: 3.0.0
info:
  title: Generación de órdenes.
  description: Api para generación de órdenes.
  version: 1.0.0
servers:
- url: /
tags:
- name: auth
  description: Acceso de usuario
- name: users
  description: Operaciones con usuarios
- name: orders
  description: Operaciones con usuarios
- name: products
  description: Operaciones con productos
paths:
  /auth:
    post:
      tags:
      - auth
      summary: Autenticación
      description: Obtención de privilegios
      operationId: authenticate
      requestBody:
        description: Usuario input
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/users'
      responses:
        "200":
          description: Autenticación exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tokenResponse'
        "401":
          description: Autenticación fallida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notAuthLogin'
        "500":
          description: Error en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internalError'
      x-swagger-router-controller: Auth
  /users/{id}:
    get:
      tags:
      - users
      summary: Buscar usuario por su id.
      description: No se requieren privilegos.
      operationId: getUserById
      parameters:
      - name: id
        in: path
        description: Order ID
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Usuario obtenido exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getUser'
        "400":
          description: Solicitud inválida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/badRequest'
        "500":
          description: Error en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internalError'
      x-swagger-router-controller: Users
    put:
      tags:
      - users
      summary: Editar información
      description: Se requieren privilegios.
      operationId: editUser
      parameters:
      - name: id
        in: path
        description: Order ID
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Usuario editado exitosamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/modifyTrue'
        "400":
          description: Solicitud inválida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/userBadRequest'
        "401":
          description: Autenticación fallida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notAuth'
        "500":
          description: Error en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internalError'
      x-swagger-router-controller: Users
    delete:
      tags:
      - users
      summary: Eliminar usuario
      description: Se requieren privilegios.
      operationId: deleteUser
      parameters:
      - name: id
        in: path
        description: Order ID
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Usuario eliminado exitosamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/deleteTrue'
        "400":
          description: Solicitud inválida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/badRequest'
        "401":
          description: Autenticación fallida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notAuth'
        "500":
          description: Error en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internalError'
      x-swagger-router-controller: Users
  /users:
    get:
      tags:
      - users
      summary: Listar usuarios
      description: No se requieren privilegos.
      operationId: getUsers
      responses:
        "200":
          description: Lista generada exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getUsers'
        "500":
          description: Error en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internalError'
      x-swagger-router-controller: Users
    post:
      tags:
      - users
      summary: Crear usuario
      description: Se requieren privilegios.
      operationId: createUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/users'
      responses:
        "200":
          description: Se requieren privilegios
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createTrue'
        "400":
          description: Solicitud inválida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/userBadRequest'
        "401":
          description: No autenticado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notAuth'
        "500":
          description: Error en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internalError'
      x-swagger-router-controller: Users
  /orders/{id}:
    get:
      tags:
      - orders
      summary: Buscar una orden por su id.
      description: No se requieren privilegos.
      operationId: getOrderById
      parameters:
      - name: id
        in: path
        description: Order ID
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Orden obtenida exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getOrder'
        "400":
          description: Solicitud inválida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/badRequest'
        "500":
          description: Error en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internalError'
      x-swagger-router-controller: Orders
    put:
      tags:
      - orders
      summary: Editar información
      description: Se requieren privilegios.
      operationId: editOrder
      parameters:
      - name: id
        in: path
        description: Order ID
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Orden editada exitosamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/modifyTrue'
        "400":
          description: Solicitud inválida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/orderBadRequest'
        "401":
          description: Autenticación fallida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notAuth'
        "500":
          description: Error en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internalError'
      x-swagger-router-controller: Orders
    delete:
      tags:
      - orders
      summary: Eliminar orden
      description: Se requieren privilegios
      operationId: deleteOrder
      parameters:
      - name: id
        in: path
        description: Order ID
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Orden eliminada exitosamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/deleteTrue'
        "400":
          description: Solicitud inválida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/badRequest'
        "401":
          description: Autenticación fallida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notAuth'
        "500":
          description: Error en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internalError'
      x-swagger-router-controller: Orders
  /orders:
    get:
      tags:
      - orders
      summary: Listar órdenes
      description: No se requieren privilegos.
      operationId: getOrders
      responses:
        "200":
          description: Lista generada exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getOrders'
        "500":
          description: Error en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internalError'
      x-swagger-router-controller: Orders
    post:
      tags:
      - orders
      summary: Crear orden
      description: Se requieren privilegios.
      operationId: createOrder
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/orders'
      responses:
        "200":
          description: Solicitud exitosa.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createTrue'
        "400":
          description: Solicitud inválida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/orderBadRequest'
        "401":
          description: No autenticado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notAuth'
        "500":
          description: Error en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internalError'
      x-swagger-router-controller: Orders
  /products/{id}:
    get:
      tags:
      - products
      summary: Buscar un producto por su id.
      description: No se requieren privilegos.
      operationId: getProductById
      parameters:
      - name: id
        in: path
        description: Product ID
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Producto obtenido exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getProduct'
        "400":
          description: Solicitud inválida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/badRequest'
        "500":
          description: Error en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internalError'
      x-swagger-router-controller: Products
    put:
      tags:
      - products
      summary: Editar información
      description: Se requieren privilegios.
      operationId: editProduct
      parameters:
      - name: id
        in: path
        description: Product ID
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Producto editado exitosamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/modifyTrue'
        "400":
          description: Solicitud inválida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/productBadRequest'
        "401":
          description: Autenticación fallida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notAuth'
        "500":
          description: Error en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internalError'
      x-swagger-router-controller: Products
    delete:
      tags:
      - products
      summary: Eliminar producto
      description: Se requieren privilegios
      operationId: deleteProduct
      parameters:
      - name: id
        in: path
        description: Order ID
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Producto eliminado exitosamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/deleteTrue'
        "400":
          description: Solicitud inválida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/badRequest'
        "401":
          description: Autenticación fallida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notAuth'
        "500":
          description: Error en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internalError'
      x-swagger-router-controller: Products
  /products:
    get:
      tags:
      - products
      summary: Listar productos
      description: No se requieren privilegos.
      operationId: getProducts
      responses:
        "200":
          description: Productos obtenidos exitosamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getProducts'
        "500":
          description: Error en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internalError'
      x-swagger-router-controller: Products
    post:
      tags:
      - products
      summary: Crear producto
      description: Se requieren privilegios.
      operationId: createProduct
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/products'
      responses:
        "200":
          description: Solicitud exitosa.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createTrue'
        "400":
          description: Solicitud inválida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/productBadRequest'
        "401":
          description: No autenticado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notAuth'
        "500":
          description: Error en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internalError'
      x-swagger-router-controller: Products
components:
  schemas:
    internalError:
      type: object
      properties:
        statusCode:
          type: integer
          example: 500
        error:
          type: string
          example: Internal Server Error
        message:
          type: string
          example: An internal server error occurred
    tokenResponse:
      type: object
      properties:
        token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjaGVjayI6dHJ1ZSwiaWF0IjoxNTksMzYwNjE0LCJleHAiOjE1OTIzNjQyMTR9.20VU1mS7WO3j87QsG_K36JHBCSoFsflITLzbJ6XW-XU
      example:
        token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjaGVjayI6dHJ1ZSwiaWF0IjoxNTksMzYwNjE0LCJleHAiOjE1OTIzNjQyMTR9.20VU1mS7WO3j87QsG_K36JHBCSoFsflITLzbJ6XW-XU
    notAuthLogin:
      type: object
      properties:
        statusCode:
          type: integer
          example: 401
        error:
          type: string
          example: Unauthorized
        message:
          type: string
          example: can't authenticate
    notAuth:
      type: object
      properties:
        statusCode:
          type: integer
          example: 401
        error:
          type: string
          example: Unauthorized
        message:
          type: string
          example: Unauthorized
    users:
      required:
      - userName
      - userPassword
      type: object
      properties:
        userName:
          maxLength: 30
          minLength: 3
          type: string
        userPassword:
          maxLength: 32
          minLength: 8
          type: string
    getUser:
      type: object
      properties:
        id:
          type: integer
          example: 1
        userName:
          type: string
          example: Arath
        createdAt:
          type: string
          example: 2020-06-15T21:33:42.000Z
        updatedAt:
          type: string
          example: 2020-06-15T21:33:42.000Z
      example:
        createdAt: 2020-06-15T21:33:42.000Z
        id: 1
        userName: Arath
        updatedAt: 2020-06-15T21:33:42.000Z
    getUsers:
      type: array
      example:
      - id: 0
        userName: User
        createdAt: 2020-06-16T23:05:14.000Z
        updatedAt: 2020-06-16T23:05:14.000Z
      - id: 3
        userName: User
        createdAt: 2020-06-16T23:05:14.000Z
        updatedAt: 2020-06-16T23:05:14.000Z
      - id: 17
        userName: User
        createdAt: 2020-06-16T23:05:14.000Z
        updatedAt: 2020-06-16T23:05:14.000Z
      - id: 21
        userName: User
        createdAt: 2020-06-16T23:05:14.000Z
        updatedAt: 2020-06-16T23:05:14.000Z
      items:
        $ref: '#/components/schemas/getUsers_inner'
    userBadRequest:
      type: object
      properties:
        statusCode:
          type: integer
          example: 400
        error:
          type: string
          example: Bad Request
        message:
          type: string
          example: '"userPassword" with value "Tklj%" fails to match the required
            pattern: /^(((?=.*[a-z])(?=.*[A-Z]))|((?=.*[a-z])(?=.*[0-9]))|((?=.*[A-Z])(?=.*[0-9])))(?=.{8,32})/'
    orders:
      required:
      - email
      - name
      - phone
      type: object
      properties:
        name:
          maxLength: 15
          minLength: 2
          type: string
        phone:
          maxLength: 15
          minLength: 8
          type: string
        email:
          type: string
          format: email
        description:
          type: string
        message:
          type: string
        value:
          maximum: 1000000
          minimum: 1
          type: integer
        deposit:
          maximum: 999999
          minimum: 1
          type: integer
    getOrder:
      properties:
        id:
          type: integer
          example: 5
        name:
          type: string
          example: Juan Carlos
        phone:
          type: string
          example: 9 3231 4311
        email:
          type: string
          example: jc.webservicdes@agilesolutions.com
        description:
          type: string
          example: Los productos adjuntos van a El litre 2390, Valparaíso
        message:
          type: string
          example: Entregar a la brevedad
        value:
          type: integer
          example: 320000
        deposit:
          type: integer
          example: 170000
        createdAt:
          type: string
          example: 2020-06-16T20:05:48.000Z
        updatedAt:
          type: string
          example: 2020-06-16T23:05:14.000Z
      example:
        createdAt: 2020-06-16T20:05:48.000Z
        phone: 9 3231 4311
        name: Juan Carlos
        description: Los productos adjuntos van a El litre 2390, Valparaíso
        deposit: 170000
        id: 5
        message: Entregar a la brevedad
        value: 320000
        email: jc.webservicdes@agilesolutions.com
        updatedAt: 2020-06-16T23:05:14.000Z
    getOrders:
      type: array
      example:
      - id: 5
        name: Nescafé 100gr
        phone: 9 3231 4311
        description: Some descriptiond
        message: And a message
        value: 320000
        deposit: 30000
        createdAt: 2020-06-16T20:05:48.000Z
        updatedAt: 2020-06-16T23:05:14.000Z
      - id: 5
        name: Leche entera 1000cc
        phone: 9 3231 4311
        description: Some descriptiond
        message: And a message
        value: 320000
        deposit: 30000
        createdAt: 2020-06-16T20:05:48.000Z
        updatedAt: 2020-06-16T23:05:14.000Z
      - id: 5
        name: Pan xl
        phone: 9 3231 4311
        description: Some descriptiond
        message: And a message
        value: 320000
        deposit: 30000
        createdAt: 2020-06-16T20:05:48.000Z
        updatedAt: 2020-06-16T23:05:14.000Z
      - id: 5
        name: Pan xl
        phone: 9 3231 4311
        description: Some descriptiond
        message: And a message
        value: 320000
        deposit: 30000
        createdAt: 2020-06-16T20:05:48.000Z
        updatedAt: 2020-06-16T23:05:14.000Z
      items:
        $ref: '#/components/schemas/getOrders_inner'
    orderBadRequest:
      type: object
      properties:
        statusCode:
          type: integer
          example: 400
        error:
          type: string
          example: Bad Request
        message:
          type: string
          example: '"phne" is not allowed'
    products:
      required:
      - category
      - name
      - value
      type: object
      properties:
        name:
          maxLength: 15
          minLength: 2
          type: string
        category:
          maxLength: 20
          minLength: 3
          type: string
        value:
          maximum: 1000000
          minimum: 1
          type: integer
        hasOffer:
          maximum: 999999
          minimum: 1
          type: integer
    getProduct:
      properties:
        id:
          type: integer
          example: 5
        name:
          type: string
          example: Nescafé 100gr
        category:
          type: string
          example: 9 3231 4311
        value:
          type: integer
          example: 320000
        hasOffer:
          type: integer
          example: 30000
        createdAt:
          type: string
          example: 2020-06-16T20:05:48.000Z
        updatedAt:
          type: string
          example: 2020-06-16T23:05:14.000Z
      example:
        createdAt: 2020-06-16T20:05:48.000Z
        name: Nescafé 100gr
        id: 5
        category: 9 3231 4311
        value: 320000
        hasOffer: 30000
        updatedAt: 2020-06-16T23:05:14.000Z
    getProducts:
      type: array
      example:
      - id: 5
        name: Nescafé 100gr
        category: 9 3231 4311
        value: 320000
        hasOffer: 30000
        createdAt: 2020-06-16T20:05:48.000Z
        updatedAt: 2020-06-16T23:05:14.000Z
      - id: 5
        name: Leche entera 1000cc
        category: 9 3231 4311
        value: 320000
        hasOffer: 30000
        createdAt: 2020-06-16T20:05:48.000Z
        updatedAt: 2020-06-16T23:05:14.000Z
      - id: 5
        name: Pan xl
        category: 9 3231 4311
        value: 320000
        hasOffer: 30000
        createdAt: 2020-06-16T20:05:48.000Z
        updatedAt: 2020-06-16T23:05:14.000Z
      - id: 5
        name: Pan xl
        category: 9 3231 4311
        value: 320000
        hasOffer: 30000
        createdAt: 2020-06-16T20:05:48.000Z
        updatedAt: 2020-06-16T23:05:14.000Z
      items:
        $ref: '#/components/schemas/getProducts_inner'
    productBadRequest:
      type: object
      properties:
        statusCode:
          type: integer
          example: 400
        error:
          type: string
          example: Bad Request
        message:
          type: string
          example: '"naaame" is not allowed'
    badRequest:
      type: object
      properties:
        statusCode:
          type: integer
          example: 400
        error:
          type: string
          example: Bad Request
        message:
          type: string
          example: Bad Request
    modifyTrue:
      type: object
      properties:
        MODIFY DATA:
          type: boolean
          example: true
      example:
        MODIFY DATA: true
    createTrue:
      type: object
      properties:
        CREATED:
          type: boolean
          example: true
      example:
        CREATED: true
    deleteTrue:
      type: object
      properties:
        DELETE DATA:
          type: boolean
          example: true
      example:
        DELETE DATA: true
    getUsers_inner:
      type: object
      properties:
        id:
          type: integer
        userName:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
    getOrders_inner:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        phone:
          type: string
        description:
          type: string
        message:
          type: string
        value:
          type: integer
        deposit:
          type: integer
        createdAt:
          type: string
        updatedAt:
          type: string
    getProducts_inner:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        category:
          type: string
        value:
          type: integer
        hasOffer:
          type: integer
        createdAt:
          type: string
        updatedAt:
          type: string
